#!/bin/bash
# Install a global `burpsuitepro` command that launches Burp with the M1kro agent.
# The command just calls run-burp.sh from this folder, so it always finds loader.jar
# and the Burp jar living next to it.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="${BIN_DIR:-/usr/local/bin}"   # override with BIN_DIR=/usr/bin ./install.sh
CMD="${CMD:-burpsuitepro}"
TARGET="$BIN_DIR/$CMD"

if [ ! -f "$HERE/run-burp.sh" ] || [ ! -f "$HERE/loader.jar" ]; then
  echo "[!] run-burp.sh or loader.jar not found in $HERE" >&2
  echo "    Run install.sh from inside the m1kro-loader folder." >&2
  exit 1
fi
chmod +x "$HERE/run-burp.sh"

SUDO=""
if [ ! -w "$BIN_DIR" ] || [ ! -d "$BIN_DIR" ]; then
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
  else
    echo "[!] Need write access to $BIN_DIR. Run as root or set BIN_DIR to a writable dir." >&2
    exit 1
  fi
fi

echo "[*] Command : $CMD"
echo "[*] Target  : $TARGET"
echo "[*] Launcher: $HERE/run-burp.sh"
[ -n "$SUDO" ] && echo "[*] (sudo needed to write into $BIN_DIR)"

tmp="$(mktemp)"
cat > "$tmp" <<EOF
#!/bin/bash
# Auto-generated by m1kro-loader install.sh — launches Burp Suite Pro with the agent.
exec "$HERE/run-burp.sh" "\$@"
EOF

$SUDO mkdir -p "$BIN_DIR"
$SUDO install -m 0755 "$tmp" "$TARGET"
rm -f "$tmp"

echo "[*] Done. Open a new terminal, then run:  $CMD"
if ! command -v "$CMD" >/dev/null 2>&1; then
  echo "[!] '$CMD' is not on PATH yet — '$BIN_DIR' may be missing from PATH."
  echo "    Add it:  echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc && source ~/.zshrc"
fi
